version: 2

# YAML Anchors for reusable configurations
x-weekly-cron: &weekly_cron
  interval: "cron"
  # every wednesday at 00:01
  cronjob: "1 0 * * 3"

x-sample-app-labels: &sample_app_labels
  - "dependencies"
  - "sample-apps"

x-sample-app-integrations-labels: &sample_app_integrations_labels
  - "dependencies"
  - "sample-apps"
  - "integrations"

x-sample-app-groups: &sample_app_groups
  sample-apps-npm-deps:
    patterns:
      - "*"
    update-types:
      - "minor"
      - "patch"
  sample-apps-npm-major-deps:
    patterns:
      - "*"
    update-types:
      - "major"

# Base template for sample apps
x-common-sample-app: &common_sample_app
  package-ecosystem: "npm"
  schedule: *weekly_cron
  target-branch: "develop"
  labels: *sample_app_labels
  groups: *sample_app_groups

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: *weekly_cron
    target-branch: "develop"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule: *weekly_cron
    target-branch: "develop"
    labels:
      - "dependencies"
    groups:
      npm-dev-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        dependency-type: "development"
      
      npm-prod-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        dependency-type: "production"

      npm-major-deps:
        patterns:
          - "*"
        update-types:
          - "major"

  # Example applications - ultra-concise with merge keys
  - <<: *common_sample_app
    directory: "/examples/angular/sample-app"

  - <<: *common_sample_app
    directory: "/examples/nextjs/hooks/sample-app"

  - <<: *common_sample_app
    directory: "/examples/nextjs/js/sample-app"

  - <<: *common_sample_app
    directory: "/examples/nextjs/page-router/sample-app"

  - <<: *common_sample_app
    directory: "/examples/nextjs/ts/sample-app"

  - <<: *common_sample_app
    directory: "/examples/reactjs/hooks/sample-app"

  - <<: *common_sample_app
    directory: "/examples/reactjs/js/sample-app"

  - <<: *common_sample_app
    directory: "/examples/reactjs/ts/sample-app"

  - <<: *common_sample_app
    directory: "/examples/reactjs/vite/sample-app"

  - <<: *common_sample_app
    directory: "/examples/gatsby/sample-gatsby-site"

  - <<: *common_sample_app
    directory: "/examples/gatsby/sample-gatsby-plugin-usage"

  - <<: *common_sample_app
    directory: "/examples/serverless/cloudflare-worker"

  - <<: *common_sample_app
    directory: "/examples/serverless/vercel-edge"

  - <<: *common_sample_app
    directory: "/examples/symfony/sample"

  # Integration examples with special labels
  - <<: *common_sample_app
    directory: "/examples/integrations/Ninetailed/sample-apps/app-using-npm"
    labels: *sample_app_integrations_labels

  - <<: *common_sample_app
    directory: "/examples/integrations/Ninetailed/sample-apps/app-using-v1.1-cdn"
    labels: *sample_app_integrations_labels

  - <<: *common_sample_app
    directory: "/examples/integrations/Ninetailed/sample-apps/app-using-v3-cdn"
    labels: *sample_app_integrations_labels
