const DEFAULT_BEACON_QUEUE_MAX_SIZE = 10;
const DEFAULT_BEACON_QUEUE_FLUSH_INTERVAL = 10 * 60 * 1000; // 10 minutes

const MAX_EVENT_PAYLOAD_SIZE_BYTES = 32 * 1024; // 32 KB

const DEFAULT_BEACON_QUEUE_OPTIONS = {
  maxItems: DEFAULT_BEACON_QUEUE_MAX_SIZE,
  flushQueueInterval: DEFAULT_BEACON_QUEUE_FLUSH_INTERVAL,
};

const REQUEST_TIMEOUT_MS = 10 * 1000; // 10 seconds

const DATA_PLANE_API_VERSION = 'v1';

const QUEUE_NAME = 'rudder';

export {
  MAX_EVENT_PAYLOAD_SIZE_BYTES,
  DEFAULT_BEACON_QUEUE_OPTIONS,
  REQUEST_TIMEOUT_MS,
  DATA_PLANE_API_VERSION,
  QUEUE_NAME,
};
