version: 0.2


phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - ls
      - npm install --unsafe-perm
      - npm run prodTest && npm test
      - npm run buildProdBrowser
      - sed 's|//# sourceMappingURL=rudder-analytics.min.js.map||' dist/rudder-analytics.min.js  > dist/prod.js
      - mv dist/prod.js dist/rudder-analytics.min.js
      - aws s3 cp dist/rudder-analytics.min.js s3://$S3_BUCKET_NAME/v3/rudder-analytics-staging.min.js --cache-control max-age=3600 --acl public-read
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/v3/rudder-analytics-staging.min.js"
artifacts:
  files:
    - "**/*"
