const FAILED_REQUEST_ERR_MSG_PREFIX = 'The request failed';
const UNHANDLEDEXCEPTION_FOR_NON_ERROR_OBJECT = 'unhandledException handler received a non-error';
const ERROR_MESSAGES_TO_BE_FILTERED = [
  FAILED_REQUEST_ERR_MSG_PREFIX,
  UNHANDLEDEXCEPTION_FOR_NON_ERROR_OBJECT,
];

export { FAILED_REQUEST_ERR_MSG_PREFIX, ERROR_MESSAGES_TO_BE_FILTERED };
