declare const DEFAULT_XHR_TIMEOUT_MS: number;
declare const DEFAULT_COOKIE_MAX_AGE_MS: number;
declare const DEFAULT_SESSION_TIMEOUT_MS: number;
declare const MIN_SESSION_TIMEOUT_MS: number;
declare const DEFAULT_DATA_PLANE_EVENTS_BUFFER_TIMEOUT_MS: number;
declare const DEBOUNCED_TIMEOUT_MS = 250;
export {
  DEFAULT_XHR_TIMEOUT_MS,
  DEFAULT_COOKIE_MAX_AGE_MS,
  DEFAULT_SESSION_TIMEOUT_MS,
  MIN_SESSION_TIMEOUT_MS,
  DEFAULT_DATA_PLANE_EVENTS_BUFFER_TIMEOUT_MS,
  DEBOUNCED_TIMEOUT_MS,
};
