name: 'Get Job URL'
description: 'Fetches the direct URL to the current GitHub Actions job'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}

outputs:
  job_url:
    description: 'Direct URL to the current job in GitHub Actions UI'
    value: ${{ steps.get-job-url.outputs.job_url }}

runs:
  using: 'composite'
  steps:
    - name: Get Job URL
      id: get-job-url
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
        echo $jobs
        job_url=$(echo "$jobs" | jq -r '.jobs[] | select(.name=="${{ github.job }}") | .html_url')
        echo "job_url=$job_url" >> $GITHUB_OUTPUT
