const DATA_PLANE_QUEUE_EXT_POINT_PREFIX = 'dataplaneEventsQueue';
const DESTINATIONS_QUEUE_EXT_POINT_PREFIX = 'destinationsEventsQueue';

export { DATA_PLANE_QUEUE_EXT_POINT_PREFIX, DESTINATIONS_QUEUE_EXT_POINT_PREFIX };
