import {
  COOKIE_STORAGE,
  LOCAL_STORAGE,
  MEMORY_STORAGE,
  SESSION_STORAGE,
} from '@rudderstack/analytics-js-common/constants/storages';
import {
  CLIENT_DATA_STORE_COOKIE,
  CLIENT_DATA_STORE_LS,
  CLIENT_DATA_STORE_MEMORY,
  CLIENT_DATA_STORE_SESSION,
} from '../../constants/storage';
export const storageClientDataStoreNameMap = {
  [COOKIE_STORAGE]: CLIENT_DATA_STORE_COOKIE,
  [LOCAL_STORAGE]: CLIENT_DATA_STORE_LS,
  [MEMORY_STORAGE]: CLIENT_DATA_STORE_MEMORY,
  [SESSION_STORAGE]: CLIENT_DATA_STORE_SESSION,
};
