declare const DEFAULT_MIN_RETRY_DELAY_MS = 1000;
declare const DEFAULT_MAX_RETRY_DELAY_MS = 30000;
declare const DEFAULT_BACKOFF_FACTOR = 2;
declare const DEFAULT_BACKOFF_JITTER = 0;
declare const DEFAULT_MAX_RETRY_ATTEMPTS: number;
declare const DEFAULT_MAX_ITEMS: number;
declare const DEFAULT_ACK_TIMER_MS = 1000;
declare const DEFAULT_RECLAIM_TIMER_MS = 3000;
declare const DEFAULT_RECLAIM_TIMEOUT_MS = 10000;
declare const DEFAULT_RECLAIM_WAIT_MS = 500;
declare const DEFAULT_MAX_BATCH_SIZE_BYTES: number;
declare const DEFAULT_MAX_BATCH_ITEMS = 100;
declare const DEFAULT_BATCH_FLUSH_INTERVAL_MS: number;
export {
  DEFAULT_MIN_RETRY_DELAY_MS,
  DEFAULT_MAX_RETRY_DELAY_MS,
  DEFAULT_BACKOFF_FACTOR,
  DEFAULT_BACKOFF_JITTER,
  DEFAULT_MAX_RETRY_ATTEMPTS,
  DEFAULT_MAX_ITEMS,
  DEFAULT_ACK_TIMER_MS,
  DEFAULT_RECLAIM_TIMER_MS,
  DEFAULT_RECLAIM_TIMEOUT_MS,
  DEFAULT_RECLAIM_WAIT_MS,
  DEFAULT_MAX_BATCH_SIZE_BYTES,
  DEFAULT_MAX_BATCH_ITEMS,
  DEFAULT_BATCH_FLUSH_INTERVAL_MS,
};
