const LOAD_CHECK_POLL_INTERVAL = 1000;
const LOAD_CHECK_TIMEOUT = 10 * LOAD_CHECK_POLL_INTERVAL;
const INITIALIZED_CHECK_POLL_INTERVAL = 100;
const INITIALIZED_CHECK_TIMEOUT = 11 * 10 * INITIALIZED_CHECK_POLL_INTERVAL;

export {
  LOAD_CHECK_POLL_INTERVAL,
  LOAD_CHECK_TIMEOUT,
  INITIALIZED_CHECK_POLL_INTERVAL,
  INITIALIZED_CHECK_TIMEOUT,
};
