// map of the destination definition names to the destination directory names
// The destination directory name is used as the destination SDK file name in CDN
const destDispNamesToFileNamesMap: Record<string, string> = {
  HubSpot: 'HubSpot',
  'Google Analytics': 'GA',
  Hotjar: 'Hotjar',
  'Google Ads': 'GoogleAds',
  VWO: 'VWO',
  'Google Tag Manager': 'GoogleTagManager',
  Braze: 'Braze',
  Intercom: 'INTERCOM',
  Keen: 'Keen',
  'Kiss Metrics': 'Kissmetrics',
  'Customer IO': 'CustomerIO',
  Chartbeat: 'Chartbeat',
  Comscore: 'Comscore',
  'Facebook Pixel': 'FacebookPixel',
  Lotame: 'Lotame',
  'Optimizely Web': 'Optimizely',
  Bugsnag: 'Bugsnag',
  Fullstory: 'Fullstory',
  TVSquared: 'TVSquared',
  'Google Analytics 4 (GA4)': 'GA4',
  MoEngage: 'MoEngage',
  Amplitude: 'Amplitude',
  Pendo: 'Pendo',
  Lytics: 'Lytics',
  Appcues: 'Appcues',
  PostHog: 'Posthog',
  Klaviyo: 'Klaviyo',
  CleverTap: 'Clevertap',
  'Bing Ads': 'BingAds',
  'Pinterest Tag': 'PinterestTag',
  'Adobe Analytics': 'AdobeAnalytics',
  'Linkedin Insight Tag': 'LinkedInInsightTag',
  'Reddit Pixel': 'RedditPixel',
  Drip: 'Drip',
  'Heap.io': 'Heap',
  Criteo: 'Criteo',
  Mixpanel: 'Mixpanel',
  Qualtrics: 'Qualtrics',
  ProfitWell: 'ProfitWell',
  Sentry: 'Sentry',
  'Quantum Metric': 'QuantumMetric',
  'Snap Pixel': 'SnapPixel',
  'Post Affiliate Pro': 'PostAffiliatePro',
  'Google Optimize': 'GoogleOptimize',
  LaunchDarkly: 'LaunchDarkly',
  'Google Analytics 360': 'GA360',
  Adroll: 'Adroll',
  'DCM Floodlight': 'DCMFloodlight',
  Matomo: 'Matomo',
  Vero: 'Vero',
  Mouseflow: 'Mouseflow',
  Rockerbox: 'Rockerbox',
  ConvertFlow: 'ConvertFlow',
  SnapEngage: 'SnapEngage',
  LiveChat: 'LiveChat',
  Shynet: 'Shynet',
  Woopra: 'Woopra',
  RollBar: 'RollBar',
  'Quora Pixel': 'QuoraPixel',
  June: 'June',
  Engage: 'Engage',
  Iterable: 'Iterable',
  'Yandex.Metrica': 'YandexMetrica',
  Refiner: 'Refiner',
  Qualaroo: 'Qualaroo',
  Podsights: 'Podsights',
  Axeptio: 'Axeptio',
  Satismeter: 'Satismeter',
  'Microsoft Clarity': 'MicrosoftClarity',
  Sendinblue: 'Sendinblue',
  Olark: 'Olark',
  Lemnisk: 'Lemnisk',
};

export { destDispNamesToFileNamesMap };
