name: Check PR Title

on:
  pull_request:
    branches: ['main', 'develop', 'hotfix/*']
    types: ['opened', 'reopened', 'edited', 'synchronize']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_pr_title:
    name: Check PR title
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@0a83071336f7d6417249629f67a64530fcecda2e # v1.0.11
