name: Check PR title v3

on:
  pull_request:
    branches: ['v3-production', 'v3-staging']
    types: ['opened', 'reopened', 'edited', 'synchronize']

jobs:
  check_pr_title:
    name: Check PR title v3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3

      - name: Check PR title
        uses: rudderlabs/github-action-check-pr-title@v1.0.7
