name: Create a new hotfix branch

on:
  workflow_dispatch:
    inputs:
      hotfix_branch_name:
        description: Hotfix branch name ('hotfix/' is automatically prepended)
        required: true

jobs:
  validate-actor:
    # Only allow creating hotfix branches from the main branch
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/validate-actor.yml
    with:
      team_names: 'sdk_team,integrations'
    secrets:
      RELEASE_PRIVATE_KEY: ${{ secrets.RELEASE_PRIVATE_KEY }}

  create-branch:
    name: Create a new hotfix branch
    runs-on: [self-hosted, Linux, X64]
    needs: validate-actor
    permissions:
      contents: write # to create branch ref via API
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PRIVATE_KEY }}
          permission-contents: write # to create branch ref via API

      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Create hotfix branch
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          REPO: ${{ github.repository }}
          HOTFIX_BRANCH_NAME: ${{ github.event.inputs.hotfix_branch_name }}
        run: |
          chmod +x scripts/create-hotfix-branch.sh
          ./scripts/create-hotfix-branch.sh "$HOTFIX_BRANCH_NAME"
