name: Create new hotfix branch v3

on:
  workflow_dispatch:
    inputs:
      hotfix_name:
        description: Hotfix branch name
        required: true

jobs:
  create-branch:
    name: Create new hotfix branch v3
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'v3-hotfix/${{ github.event.inputs.hotfix_name }}'
