name: Deploy to Development Environment

on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
    types:
      - closed

jobs:
  validate-actor:
    # Run only for workflow_dispatch events with a merged pull request
    if: >
      github.event_name == 'workflow_dispatch' &&
      github.event.pull_request.merged == true
    uses: ./.github/workflows/validate-actor.yml
    secrets:
      PAT: ${{ secrets.PAT }}

  deploy:
    needs: [validate-actor]
    name: Deploy to Development Environment
    if: >
      (needs.validate-actor.result == 'success' || needs.validate-actor.result == 'skipped') &&
      github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'development'
      bugsnag_release_stage: 'development'
      s3_dir_path: 'dev/latest/v3'
      s3_dir_path_legacy: 'dev/latest/v1.1'
      action_type: ''
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_DEV_S3_BUCKET_NAME }}
      AWS_S3_SYNC_ROLE: ${{ secrets.AWS_DEV_S3_SYNC_ROLE }}
      AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_DEV_CF_DISTRIBUTION_ID }}
      BUGSNAG_API_KEY: ${{ secrets.RS_PROD_BUGSNAG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_RELEASE_CHANNEL_ID: ${{ secrets.SLACK_RELEASE_CHANNEL_ID_NON_PROD }}

  deploy-sanity-suite:
    name: Deploy sanity suite
    needs: deploy
    uses: ./.github/workflows/deploy-sanity-suite.yml
    with:
      environment: 'development'
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_DEV_S3_BUCKET_NAME }}
      AWS_S3_SYNC_ROLE: ${{ secrets.AWS_DEV_S3_SYNC_ROLE }}
      AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_DEV_CF_DISTRIBUTION_ID }}
      SANITY_SUITE_WRITE_KEY: ${{ secrets.SANITY_SUITE_DEV_WRITE_KEY }}
      SANITY_SUITE_DATAPLANE_URL: ${{ secrets.SANITY_SUITE_DEV_DATAPLANE_URL }}
      SANITY_SUITE_CONFIG_SERVER_HOST: ${{ secrets.SANITY_SUITE_DEV_CONFIG_SERVER_HOST }}
      BUGSNAG_API_KEY: ${{ secrets.RS_DEV_BUGSNAG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_RELEASE_CHANNEL_ID: ${{ secrets.SLACK_RELEASE_CHANNEL_ID_NON_PROD }}

  trigger-test-suites:
    uses: ./.github/workflows/trigger-test-suites.yml
    name: Trigger test suites
    needs: deploy-sanity-suite
    with:
      environment: development
    secrets:
      PAT: ${{ secrets.PAT }}
