name: Deploy to Development Environment

on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
    types:
      - closed

jobs:
  deploy:
    name: Deploy to development environment
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'development'
      bugsnag_release_stage: 'development'
      s3_dir_path: 'dev/latest/v3'
      s3_dir_path_legacy: 'dev/latest/v1.1'
      action_type: ''
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_DEV_S3_BUCKET_NAME }}
      AWS_S3_SYNC_ROLE: ${{ secrets.AWS_DEV_S3_SYNC_ROLE }}
      AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_DEV_CF_DISTRIBUTION_ID }}
      BUGSNAG_API_KEY: ${{ secrets.RS_PROD_BUGSNAG_API_KEY }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_RELEASE_CHANNEL_ID: ${{ secrets.SLACK_RELEASE_CHANNEL_ID_NON_PROD }}
