name: Draft new release v1

on:
  workflow_dispatch:

jobs:
  draft-new-release:
    name: Draft a new release v1
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/v1-staging') || startsWith(github.ref, 'refs/heads/v1-hotfix')
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      # Calculate the next release version based on conventional semantic release
      - name: Create release branch
        id: create-release
        env:
          HUSKY: 0
        run: |
          source_branch_name=${GITHUB_REF##*/}
          release_type=v1-release
          grep -q "v1-hotfix" <<< "${GITHUB_REF}" && release_type=v1-hotfix-release
          git fetch origin v1-production
          git fetch --tags origin
          git merge origin/v1-production
          current_version=$(jq -r .version package.json)
          npx standard-version --skip.commit --skip.tag --skip.changelog
          new_version=$(jq -r .version package.json)
          git reset --hard
          branch_name="${release_type}/${new_version}"
          echo "Source branch for new release is $source_branch_name"
          echo "Current version is $current_version"
          echo "Release type is $release_type"
          echo "New version is $new_version"
          echo "New release branch name is $branch_name"
          git checkout -b "$branch_name"
          git push --set-upstream origin "$branch_name"
          echo "source_branch_name=$source_branch_name" >> $GITHUB_OUTPUT
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "CURRENT_VERSION_VALUE=$current_version" >> $GITHUB_ENV
          echo "NEW_VERSION_VALUE=$new_version" >> $GITHUB_ENV

      - name: Update changelog & bump version
        id: finish-release
        env:
          HUSKY: 0
        run: |
          npx standard-version -a --skip.tag

      - name: Push new version in release branch & tag
        run: |
          git push

      - name: Create pull request into v1-production
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.create-release.outputs.branch_name }}
          destination_branch: 'v1-production'
          github_token: ${{ secrets.PAT }}
          pr_title: 'chore(release): pulling ${{ steps.create-release.outputs.branch_name }} into v1-production'
          pr_body: ":crown: *An automated PR*"
          pr_reviewer: 'bardisg,MoumitaM,saikumarrs'
