name: Publish New Release to GitHub

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  NODE_OPTIONS: '--no-warnings'

jobs:
  release:
    name: Publish new release
    runs-on: ubuntu-latest
    # only merged pull requests must trigger this job
    if: (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix-release/')) && github.event.pull_request.merged == true

    steps:
      - name: Extract version from branch name (for release branches)
        id: extract-version
        env:
          BRANCH_NAME_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          BRANCH_NAME="${BRANCH_NAME_REF}"
          VERSION=${BRANCH_NAME#hotfix-}
          VERSION=${VERSION#release/}

          echo "release_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        env:
          HUSKY: 0
        run: |
          npm run setup:ci

      # In order to make a commit, we need to initialize a user.
      # You may choose to write something less generic here if you want, it doesn't matter functionality wise.
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Create monorepo release tag
        id: create_monorepo_release
        run: |
          git tag -a v${{ steps.extract-version.outputs.release_version }} -m "chore(monorepo): release v${{ steps.extract-version.outputs.release_version }}"
          git push origin refs/tags/v${{ steps.extract-version.outputs.release_version }}

      - name: Get the two latest versions
        run: |
          CURRENT_VERSION=$(git tag -l "v3*" --sort=-version:refname | head -n 1)
          LAST_VERSION=$(git tag -l "v3*" --sort=-version:refname | head -n 2 | awk 'NR == 2 { print $1 }')

          echo "Current version: $CURRENT_VERSION"
          echo "Previous version: $LAST_VERSION"

          echo "current_monorepo_version=$(echo $CURRENT_VERSION)" >> $GITHUB_ENV
          echo "last_monorepo_version=$(echo $LAST_VERSION)" >> $GITHUB_ENV
          echo "DATE=$(date)" >> $GITHUB_ENV

      - name: Create GitHub releases
        id: create_release
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run release:github -- --base=${{ env.last_monorepo_version }} --head=${{ env.current_monorepo_version }}

      - name: Create pull request into develop
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'main'
          destination_branch: 'develop'
          github_token: ${{ secrets.PAT }}
          pr_title: 'chore(release): pull main into develop post release v${{ steps.extract-version.outputs.release_version }}'
          pr_body: ':crown: *An automated PR*'
          pr_reviewer: 'MoumitaM,saikumarrs'

      - name: Delete hotfix release branch
        uses: koj-co/delete-merged-action@master
        if: startsWith(github.event.pull_request.head.ref, 'hotfix-release/')
        with:
          branches: 'hotfix-release/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete release branch
        uses: koj-co/delete-merged-action@master
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        with:
          branches: 'release/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send message to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          PROJECT_NAME: 'JS SDK (v3) monorepo'
          RELEASES_URL: 'https://github.com/rudderlabs/rudder-sdk-js/compare/'
        with:
          channel-id: ${{ secrets.SLACK_RELEASE_CHANNEL_ID }}
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New release: ${{ env.PROJECT_NAME }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Release: <${{env.RELEASES_URL}}${{ env.last_monorepo_version }}...v${{ steps.extract-version.outputs.release_version }}|v${{ steps.extract-version.outputs.release_version }}>*\n${{ env.DATE }}"
                  }
                }
              ]
            }
