name: 'Unit Tests, Coverage & Sonar v3'

on:
  workflow_dispatch:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop', 'v3-hotfix/*']
    types: ['opened', 'reopened', 'synchronize']

env:
  NODE_OPTIONS: "--no-warnings"

jobs:
  build:
    name: 'Unit Tests, Coverage & Sonar v3'
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - name: Login to DockerHub
#        uses: docker/login-action@v3.0.0
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        env:
          HUSKY: 0
        run: |
          npm run setup:ci

      - name: Execute unit tests
        run: |
          npm run test:ci

      - name: Execute linting check
        run: |
          npm run check:lint:ci

      - name: Fix filesystem paths in generated reports
        run: |
          ./scripts/fix-reports-path-in-github-runner

      - name: Upload report to github build
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: packages/analytics-js/reports

#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
