name: debug token workflow call

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    name: token debug
    uses: ./.github/workflows/token.yaml
    secrets:
      AWS_DEV_ACCOUNT_ID: ${{ secrets.AWS_DEV_ACCOUNT_ID }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_DEV_S3_BUCKET_NAME }}
      AWS_S3_SYNC_ROLE: ${{ secrets.AWS_DEV_S3_SYNC_ROLE }}
