name: Run sanity suite on BrowserStack

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select specific environment to run the tests
        options:
          - staging
          - production
      monorepoVersion:
        description: Version of the Monorepo
        required: true
  workflow_call:
    inputs:
      environment:
        type: string
        default: production
    secrets:
      PAT:
        description: Personal Access Token
        required: true

jobs:
  extract-monorepo-version:
    name: Extract Monorepo Version
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.determine_version.outputs.current_version }}

    steps:
      - name: Determine checkout SHA
        id: getSHA
        run: |
          if [ "${{ github.event.inputs.environment || inputs.environment }}" = 'staging' ]; then
            sha=${{ github.event.pull_request.head.sha }}
          else
            sha=${{ github.sha }}
          fi
          echo "Checkout SHA: $sha"
          echo "SHA=$sha" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.getSHA.outputs.SHA }}

      - name: Determine the Monorepo version
        id: determine_version
        run: |
          if [ -n "${{ github.event.inputs.monorepoVersion }}" ]; then
            current_version="${{ github.event.inputs.monorepoVersion }}"
          else
            current_version=$(jq -r .version package.json)
          fi
          echo "current_version=$current_version" >> $GITHUB_OUTPUT

  trigger:
    runs-on: [self-hosted, Linux, X64]
    needs: extract-monorepo-version

    steps:
      - name: Trigger sanity suite test workflow on rudder-client-side-test
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/rudderlabs/rudder-client-side-test/dispatches \
          -d '{"event_type":"triggered_by_source_repo", "client_payload": {"environment": "${{ github.event.inputs.environment || inputs.environment }}", "monorepoVersion": "${{ needs.extract-monorepo-version.outputs.version }}"}}'
