name: Validate Actor

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  validate-actor:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Validate if actor is allowed to trigger the workflow
        env:
          ORG_NAME: rudderlabs
          TEAM_NAME: js-sdk
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          actor=${{ github.actor || github.triggering_actor }}
          
          # Use gh api to fetch the membership details
          response=$(gh api "/orgs/$ORG_NAME/teams/$TEAM_NAME/memberships/$actor" -H "X-GitHub-Api-Version: 2022-11-28" 2>/dev/null || echo "error")
          
          # Check if API request failed
          if [ "$response" = "error" ]; then
            echo "Error: Unable to fetch membership details for '$actor'."
            exit 1
          fi

          echo "Response: $response"

          # Extract the state of the membership
          if echo "$response" | grep -q '"state":"active"'; then
            echo "'$actor' is a member of '@${ORG_NAME}/${TEAM_NAME}' team"
          else
            echo "Error: '$actor' is NOT a member of '@${ORG_NAME}/${TEAM_NAME}' team. Access denied."
            exit 1
          fi

