name: Validate Actor

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  validate-actor:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Validate if actor is allowed to trigger the workflow
        env:
          ORG_NAME: rudderlabs
          TEAM_NAME: js-sdk
        run: |
          actor=${{ github.actor || github.triggering_actor }}
          response=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{ env.ORG_NAME }}/teams/${{ env.TEAM_NAME }}/memberships/$actor)
          
          if echo "$response" | grep -q '"state": "active"'; then
            echo "$actor is a member of $TEAM_NAME team"
          else
            echo "$actor is NOT a member of $TEAM_NAME team"
            exit 1
          fi
